spring:
  datasource:
    url: jdbc:h2:mem:jwt-connect
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
